[package]
name = "fractal"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
winit = "0.30"
bytemuck = { version = "1.25", features = ["derive"] }
glam = { version = "0.33", features = ["bytemuck", "encase"] }
encase = "0.12"
dashu = "0.4"
wgpu = "29"
pollster = "0.4"
num_cpus = "1.17"
parking_lot = "0.12"

[lib]
bench = false

[[bin]]
name = "fractal"
path = "src/main.rs"
bench = false

[dev-dependencies]
image = "0.25"
criterion = "0.8"

[[bench]]
name = "mandelbrot_simd"
harness = false

[profile.release]
opt-level = 3         # Apply the highest level of optimizations.
lto = true            # Enable Link Time Optimization
codegen-units = 1     # Reduce parallel code generation which can improve optimizations
